"""
API Generator V2 - Uses Python introspection to generate unified API.

This version uses isolated subprocess introspection to avoid dependency conflicts.
Each server is introspected in its own Python environment.
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from typing import Dict, List, Any, Tuple
from jinja2 import Template


class UnifiedAPIGenerator:
    """Generates unified API using Python introspection."""

    def __init__(self):
        self.api_template = """# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by mcp-tools-orchestrator using Python introspection
# This module provides a unified API for tools from multiple MCP servers
# Tool calls are routed through the mcp-client's IPC server

import requests
import json
from typing import Dict, Any, Optional, List

_IPC_URL = "{{ client_ipc_url }}"

{% for server_name, tools in servers.items() %}
# ============================================================================
# Tools from: {{ server_name }}
# ============================================================================
{% for tool in tools %}

def {{ server_name.replace('-', '_') }}__{{ tool.name }}({{ tool.params_str }}) -> dict:
    \"\"\"{{ tool.docstring }}\"\"\"
    return _call_tool("{{ server_name }}", "{{ tool.original_name }}", {{ tool.args_dict }})
{% endfor %}
{% endfor %}

# ============================================================================
# Internal helper function
# ============================================================================

def _call_tool(server: str, tool: str, arguments: dict) -> dict:
    \"\"\"Internal function to call MCP tool via IPC server.

    Args:
        server: Server name
        tool: Tool name
        arguments: Tool arguments

    Returns:
        Tool execution result (parsed from JSON if necessary)
    \"\"\"
    try:
        response = requests.post(
            f"{_IPC_URL}/call_tool",
            json={
                "server": server,
                "tool": tool,
                "arguments": arguments
            },
            timeout=300  # 5 minute timeout
        )
        response.raise_for_status()

        # Get IPC response
        data = response.json()

        # Check if tool call was successful
        if not data.get("success"):
            return {
                "error": data.get("error", "Unknown error"),
                "status": "error"
            }

        # Extract result from IPC response
        result = data.get("result")

        # Parse if it's a JSON string (common for MCP tools that return dicts)
        if isinstance(result, str):
            try:
                return json.loads(result)
            except (json.JSONDecodeError, ValueError):
                # Not valid JSON, return as-is
                return result

        return result

    except requests.exceptions.HTTPError as e:
        # Check for abort signal in HTTP errors
        if e.response is not None and e.response.status_code == 500:
            try:
                error_data = e.response.json()
                # Detect abort signal
                if (error_data.get("aborted") or
                    "[ABORTED]" in str(error_data.get("error", ""))):
                    # Print clear abort message to stderr
                    import sys
                    print("\\n[ABORTED] Operation cancelled by user - waiting for further input from the user", file=sys.stderr)
                    # Stop script execution immediately (no message to avoid duplication)
                    raise SystemExit(1)
            except (ValueError, KeyError):
                # Not JSON or missing expected fields, treat as regular error
                pass

        # Handle other HTTP errors normally
        return {
            "error": f"Failed to call tool {server}__{tool}: {str(e)}",
            "status": "error"
        }

    except requests.exceptions.RequestException as e:
        return {
            "error": f"Failed to call tool {server}__{tool}: {str(e)}",
            "status": "error"
        }
"""

    def build_function_signature(self, tool_info: dict) -> Tuple[str, str]:
        """Build function signature from introspection data.

        Args:
            tool_info: Dictionary with tool signature information

        Returns:
            (params_str, args_dict)
        """
        params = []
        args = []

        # Basic types that are safe to include in generated code
        safe_types = {'str', 'int', 'float', 'bool', 'dict', 'list', 'tuple', 'set', 'Any', 'Optional', 'Dict', 'List'}

        for param_info in tool_info.get('params', []):
            name = param_info['name']
            annotation = param_info.get('annotation')
            has_default = param_info.get('has_default', False)
            default = param_info.get('default')

            # Build parameter string
            use_type = annotation and (annotation in safe_types or annotation.startswith('typing.'))

            if has_default:
                if use_type:
                    params.append(f"{name}: {annotation} = {default}")
                else:
                    params.append(f"{name} = {default}")
            else:
                if use_type:
                    params.append(f"{name}: {annotation}")
                else:
                    params.append(name)

            # Build arguments dictionary
            args.append(f'"{name}": {name}')

        params_str = ", ".join(params)
        args_dict = "{" + ", ".join(args) + "}" if args else "{}"

        return params_str, args_dict

    def discover_tools_subprocess(
        self,
        python_path: str,
        server_path: str,
        server_name: str,
        exclude_tools: List[str] = None
    ) -> List[Dict[str, Any]]:
        """Discover tools using subprocess introspection.

        Runs the introspection script in the server's own Python environment
        to avoid dependency conflicts.
        """
        exclude_tools = exclude_tools or []
        introspect_script = Path(__file__).parent / "introspect_server.py"

        # Build command
        cmd = [python_path, str(introspect_script), server_path, ",".join(exclude_tools)]

        try:
            # Run introspection in isolated subprocess
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode != 0:
                print(f"[Orchestrator] Introspection failed for {server_name}: {result.stderr}")
                return []

            # Parse JSON output
            data = json.loads(result.stdout)

            if not data.get('success'):
                print(f"[Orchestrator] Introspection error for {server_name}: {data.get('error')}")
                return []

            # Convert introspection data to tool definitions
            tools = []
            for tool_info in data.get('tools', []):
                tool_name = tool_info['name']

                if tool_name in exclude_tools:
                    continue

                params_str, args_dict = self.build_function_signature(tool_info)
                docstring = tool_info.get('docstring', f"[{server_name}] {tool_name}")

                tools.append({
                    'name': tool_name.replace('-', '_'),
                    'original_name': tool_name,
                    'params_str': params_str,
                    'args_dict': args_dict,
                    'docstring': docstring.replace('"', '\\"').replace('\n', '\\n')
                })

            return tools

        except subprocess.TimeoutExpired:
            print(f"[Orchestrator] Introspection timeout for {server_name}")
            return []
        except json.JSONDecodeError as e:
            print(f"[Orchestrator] Failed to parse introspection output for {server_name}: {e}")
            print(f"[Orchestrator] Output was: {result.stdout[:500]}")
            return []
        except Exception as e:
            print(f"[Orchestrator] Unexpected error introspecting {server_name}: {e}")
            import traceback
            traceback.print_exc()
            return []

    def generate_api_from_config(
        self,
        config_path: str,
        output_path: str,
        client_ipc_url: str
    ):
        """Generate unified API from server configuration file.

        Args:
            config_path: Path to mcp_servers_config.json
            output_path: Path to write the generated unified_api.py
            client_ipc_url: URL of the client's IPC server
        """
        import json

        # Load config
        with open(config_path, 'r') as f:
            config = json.load(f)

        servers = {}

        for server_name, server_config in config['mcpServers'].items():
            if server_config.get('disabled', False):
                print(f"[Orchestrator] Skipping disabled server: {server_name}")
                continue

            # Extract server.py path and Python interpreter from config
            if server_config['type'] == 'stdio':
                if server_config['command'] == 'bash':
                    # Parse from bash -c command (ros-mcp-server case)
                    bash_cmd = server_config['args'][1]  # Get the command string
                    parts = bash_cmd.split()
                    # Find the Python path and server path
                    python_path = None
                    server_path = None
                    for i, part in enumerate(parts):
                        if part.endswith('/python') and i + 1 < len(parts):
                            python_path = part
                            server_path = parts[i + 1]
                            break
                    if not python_path or not server_path:
                        print(f"[Orchestrator] Could not parse bash command for {server_name}")
                        continue
                else:
                    # Direct Python command (isaac-sim, Resources)
                    python_path = server_config['command']
                    server_path = server_config['args'][0]

                print(f"[Orchestrator] Discovering tools from {server_name}: {server_path}")
                print(f"[Orchestrator] Using Python: {python_path}")

                # Discover tools using subprocess introspection
                tools = self.discover_tools_subprocess(python_path, server_path, server_name, exclude_tools=None)

                if tools:
                    servers[server_name] = tools
                    print(f"[Orchestrator] Found {len(tools)} tools from {server_name}")
                else:
                    print(f"[Orchestrator] No tools discovered from {server_name}")

        # Generate the API file
        template = Template(self.api_template)
        generated_code = template.render(
            servers=servers,
            client_ipc_url=client_ipc_url
        )

        # Write to file
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        with open(output_file, 'w') as f:
            f.write(generated_code)

        total_tools = sum(len(tools) for tools in servers.values())
        print(f"[Orchestrator] Generated unified API at: {output_path}")
        print(f"[Orchestrator] Total: {len(servers)} servers, {total_tools} tools")

        return output_path


if __name__ == "__main__":
    """Test the generator standalone."""
    import sys

    if len(sys.argv) < 2:
        print("Usage: python api_generator.py <config_path> [output_path] [ipc_url]")
        sys.exit(1)

    config_path = sys.argv[1]
    output_path = sys.argv[2] if len(sys.argv) > 2 else "generated/unified_api.py"
    ipc_url = sys.argv[3] if len(sys.argv) > 3 else "http://localhost:38039"

    generator = UnifiedAPIGenerator()
    generator.generate_api_from_config(config_path, output_path, ipc_url)

    print("\n✓ API generation complete!")
